server:
  port: 8081

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        namespace: ${NACOS_NAMESPACE:public}
        bootstrap:
          enable: ${NACOS_BOOTSTRAP_ENABLE:true}
        server-addr: 127.0.0.1:8848
        remote-first: ${NACOS_REMOTE_FIRST:true}
        data-id: demo-alibaba
        type: yaml
        auto-refresh: true
        group: ${NACOS_GROUP:consumer}
##        username: mumway_nacos_prod
##        password: YUcS5QhI0G7WIKc5